In [1]:
import pandas as pd
import numpy as np

dnkn = pd.read_csv('BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv')

In [2]:
dnkn.info()

<class 'pandas.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Category             780 non-null    str
 1   Item                 780 non-null    str
 2   Calories             780 non-null    str
 3   Total Fat (g)        780 non-null    str
 4   Saturated Fat (g)    780 non-null    str
 5   Trans Fat (g)        780 non-null    str
 6   Cholesterol (mg)     780 non-null    str
 7   Sodium (mg)          780 non-null    str
 8   Carbs (g)            780 non-null    str
 9   Fiber (g)            780 non-null    str
 10  Sugars (g)           780 non-null    str
 11  Protein (g)          780 non-null    str
 12  Weight Watcher Pnts  780 non-null    str
dtypes: str(13)
memory usage: 132.8 KB

In [3]:
dnkn.isnull().sum()

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

In [4]:
dnkn.duplicated().sum()

np.int64(1)

In [5]:
dnkn[dnkn.duplicated()]

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
760,Sandwiches,Ham and Cheese Rollups,280,13,6,0,40,1050,27,1,2,13,275

In [6]:
dnkn.nunique()

Category                23
Item                   779
Calories                87
Total Fat (g)           50
Saturated Fat (g)       29
Trans Fat (g)            5
Cholesterol (mg)        37
Sodium (mg)            112
Carbs (g)              120
Fiber (g)                9
Sugars (g)             122
Protein (g)             32
Weight Watcher Pnts    362
dtype: int64

In [7]:
dnkn['Category'].value_counts()

Category
Hot Coffee            88
Donuts                87
Hot Latte             63
Iced Coffee           63
Iced Latte            63
Sandwiches            55
Frozen Coffee         49
Hot Macchiato         45
Hot Cappuccino        43
Iced Cappuccino       42
Iced Macchiato        42
Iced Tea              33
Hot Chocolate         28
Muffins               18
Kolache               16
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Hash Browns            1
Dunkin’ Bowls          1
Name: count, dtype: int64

In [8]:
dnkn.describe(include='all')

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
count,780,780,780,780,780,780,780,780,780,780,780,780,780
unique,23,779,87,50,29,5,37,112,120,9,122,32,362
top,Hot Coffee,Ham and Cheese Rollups,170,0,0,0,0,180,35,0,0,4,5
freq,88,2,38,242,269,755,222,24,30,508,33,94,13

In [9]:
print("Cholesterol Values:", dnkn['Cholesterol (mg)'].unique())
print("Trans Fat Values:", dnkn['Trans Fat (g)'].unique())

Cholesterol Values: <ArrowStringArray>
[  '0',  '35',  '25',  '20',  '15',  '10',  '50',  '30',  '40', '130', '100',
  '70', '105',  '80',  '55',  '<5',   ' ', '125',  '45',  '60', '185', '340',
 '180',  '95',  '65', '190', '360', '195', '265', '175', '220', '120', '200',
 '240', '205', '110', '115']
Length: 37, dtype: str
Trans Fat Values: <ArrowStringArray>
['0', '1.5', '1', '0.5', ' ']
Length: 5, dtype: str

In [10]:
dnkn1 = dnkn.copy()

In [11]:
food_items = ['Donuts', 'Muffins', 'Kolache', 'Sandwiches', 'Hash Browns']
dnkn1 = dnkn1[~dnkn1['Category'].isin(food_items)].copy()

In [12]:
dnkn1.duplicated().sum()

np.int64(0)

In [13]:
dnkn2 = dnkn1.copy()
dnkn2['Cholesterol (mg)'] = dnkn2['Cholesterol (mg)'].replace('<5', '5')

for col in dnkn2.select_dtypes(include='object').columns:
    dnkn2[col] = (
        dnkn2[col]
        .str.replace('\xa0', '', regex=False)
        .str.strip()
    )

C:\Users\Elijah\AppData\Local\Temp\ipykernel_9340\838965216.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in dnkn2.select_dtypes(include='object').columns:

In [14]:
for col in dnkn2.columns:
    if dnkn2[col].dtype == 'object':
        print('\n', col)
        print(dnkn2[col].unique()[:50])

In [15]:
dnkn2 = dnkn2.replace('', np.nan)

In [16]:
dnkn2.isnull().sum()

Category               0
Item                   0
Calories               3
Total Fat (g)          3
Saturated Fat (g)      3
Trans Fat (g)          3
Cholesterol (mg)       3
Sodium (mg)            3
Carbs (g)              3
Fiber (g)              3
Sugars (g)             3
Protein (g)            3
Weight Watcher Pnts    3
dtype: int64

In [17]:
dnkn3 = dnkn2.dropna().copy()

In [18]:
dnkn3.isnull().sum()

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

In [19]:
numeric_columns = [
    'Calories', 'Total Fat (g)', 'Saturated Fat (g)', 'Trans Fat (g)', 
    'Cholesterol (mg)', 'Sodium (mg)', 'Carbs (g)', 'Fiber (g)', 
    'Sugars (g)', 'Protein (g)', 'Weight Watcher Pnts'
]

for col in numeric_columns:
    dnkn3[col] = pd.to_numeric(dnkn3[col])

In [20]:
print("================ MISSING VALUES ================")
print(dnkn3.isnull().sum())

print("\n================ DATA TYPES ================")
print(dnkn3.dtypes)

print("\n================ DUPLICATE RECORDS ================")
print("Duplicates:", dnkn3.duplicated().sum())

print("\n================ CATEGORY CHECK ================")
print(dnkn3['Category'].value_counts())

print("\n================ DATASET SHAPE ================")
print(dnkn3.shape)

print("\n================ SUMMARY STATISTICS ================")
print(dnkn3.describe().round(2))

================ MISSING VALUES ================
Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

================ DATA TYPES ================
Category                   str
Item                       str
Calories                 int64
Total Fat (g)          float64
Saturated Fat (g)      float64
Trans Fat (g)          float64
Cholesterol (mg)         int64
Sodium (mg)              int64
Carbs (g)                int64
Fiber (g)                int64
Sugars (g)               int64
Protein (g)              int64
Weight Watcher Pnts    float64
dtype: object

================ DUPLICATE RECORDS ================
Duplicates: 0

================ CATEGORY CHECK ================
Category
Hot Coffee            88
Hot Latte             63
Iced Coffee           63
Iced Latte            63
Frozen Coffee         47
Hot Macchiato         45
Hot Cappuccino        42
Iced Cappuccino       42
Iced Macchiato        42
Iced Tea              33
Hot Chocolate         28
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Dunkin’ Bowls          1
Name: count, dtype: int64

================ DATASET SHAPE ================
(600, 13)

================ SUMMARY STATISTICS ================
       Calories  Total Fat (g)  Saturated Fat (g)  Trans Fat (g)  \
count    600.00         600.00             600.00         600.00
mean     253.32           5.05               3.04           0.03
std      183.27           6.37               3.98           0.16
min        5.00           0.00               0.00           0.00
25%      130.00           0.00               0.00           0.00
50%      230.00           4.00               2.50           0.00
75%      340.00           8.00               4.50           0.00
max     1160.00          40.00              22.00           1.50

       Cholesterol (mg)  Sodium (mg)  Carbs (g)  Fiber (g)  Sugars (g)  \
count            600.00       600.00     600.00     600.00      600.00
mean              15.39       140.01      45.98       0.34       42.72
std               18.43       112.21      35.12       0.74       33.02
min                0.00         5.00       0.00       0.00        0.00
25%                0.00        60.00      25.00       0.00       23.00
50%               10.00       120.00      40.00       0.00       38.00
75%               25.00       190.00      63.00       0.00       57.00
max              130.00       750.00     195.00       4.00      185.00

       Protein (g)  Weight Watcher Pnts
count       600.00               600.00
mean          6.01               293.08
std           4.18               215.37
min           0.00                 4.00
25%           2.00               156.75
50%           6.00               265.75
75%           9.00               386.00
max          19.00              1352.00

In [21]:
dnkn3.to_csv('dnkn_clean.csv', index=False)

In [22]:
dnkn4 = pd.read_csv('dnkn_clean.csv')
dnkn4.head()

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0.0,0.0,0.0,0,20,0,0,0,1,4.0
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0.0,0.0,0.0,0,15,0,0,0,0,5.0
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0.0,0.0,0.0,0,10,0,0,0,0,5.0
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12.0,6.0,0.0,35,65,2,0,2,2,126.0
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9.0,4.5,0.0,25,45,1,0,1,2,93.5